# Generated by Django 6.0.1 on 2026-02-24 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialdkp',
            options={'ordering': ['-fecha'], 'verbose_name': 'Registro de Historial', 'verbose_name_plural': 'Historial de Puntos'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil de Jugador', 'verbose_name_plural': 'Perfiles de Jugadores'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='aprobado',
            field=models.BooleanField(default=False, verbose_name='Aprobado por Staff'),
        ),
        migrations.AlterField(
            model_name='historialdkp',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad de Puntos'),
        ),
        migrations.AlterField(
            model_name='historialdkp',
            name='evento',
            field=models.CharField(max_length=200, verbose_name='Motivo / Evento'),
        ),
        migrations.AlterField(
            model_name='historialdkp',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='historialdkp',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.perfil', verbose_name='Jugador'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='asistencia_porcentaje',
            field=models.IntegerField(default=0, verbose_name='% Asistencia'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Avatar'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='discord_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Discord'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='dkp_actuales',
            field=models.IntegerField(default=0, verbose_name='Puntos DKP'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='eventos_participados',
            field=models.IntegerField(default=0, verbose_name='Raids Totales'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rango',
            field=models.CharField(default='Miembro', max_length=50, verbose_name='Rango del Clan'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
